name: "CI"

on:
  push:
    branches:
      - '*'

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --prefer-dist"
  PHP_VERSION: 8.2

jobs:
  static_analysis:
    name: "Lint & PHPStan"

    runs-on: ubuntu-20.04

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "intl, zip, xml"
          tools: phive
          ini-values: "memory_limit=-1"
          php-version: ${{ env.PHP_VERSION }}

      - name: "Install dependencies from composer.lock"
        run: "composer install --no-scripts ${{ env.COMPOSER_FLAGS }}"

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: echo "directory"="$(composer config -g cache-dir)" >> $GITHUB_OUTPUT

      - name: "Cache composer cache dir"
        if: "steps.cache-vendor-dir.outputs.cache-hit != 'true'"
        uses: "actions/cache@v3"
        with:
          path: |
            ${{ steps.determine-composer-cache-directory.outputs.directory }}
          key: "composer-cache-${{ hashFiles('*/composer.lock') }}-locked"
          restore-keys: "composer-cache-"

      - name: "Install tools"
        run: "phive install --force-accept-unsigned --trust-gpg-keys 4AA394086372C20A,51C67305FFC2E5C0"

      - name: "Lint PHP files"
        run: "tools/parallel-lint src"

      - name: "Run PHPStan"
        run: "tools/phpstan analyze src"

  tests:
    name: "Tests"

    runs-on: ubuntu-20.04
    continue-on-error: false

    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0', '8.1', '8.2', '8.3']

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          extensions: "intl, zip, xml"
          ini-values: "memory_limit=-1,display_errors=1"
          php-version: ${{ matrix.php-versions }}
          tools: "phive"

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config -g cache-dir)\""

      - name: "Cache composer cache dir"
        if: "steps.cache-vendor-dir.outputs.cache-hit != 'true'"
        uses: "actions/cache@v3"
        with:
          path: |
            ${{ steps.determine-composer-cache-directory.outputs.directory }}
          key: "composer-cache-${{ hashFiles('*/composer.lock') }}-locked"
          restore-keys: "composer-cache-"

      - name: "Install dependencies from composer.lock"
        run: "composer install ${{ env.COMPOSER_FLAGS }}"

      - name: "Install tools"
        run: "phive install --force-accept-unsigned --trust-gpg-keys 4AA394086372C20A,51C67305FFC2E5C0"

      - name: "Run tests"
        run: "tools/phpunit"
